--
--DROP TABLES
--	
DROP TABLE Accounts CASCADE;
DROP TABLE Messages CASCADE;
DROP TABLE Patient_Account CASCADE;
DROP TABLE HCP_Account CASCADE;
DROP TABLE Appointments CASCADE;
DROP TABLE Medical_Record CASCADE;
DROP TABLE Payment CASCADE;
DROP TABLE P_D_Connection CASCADE;
DROP TABLE D_D_Connection CASCADE;
DROP TABLE Permission CASCADE;

